### ISSUE TITLE
ZeroMQ transport not shutting down on termination.

### ISSUE THREAD

**Issue by huxoll** [cjmamo/mule-transport-zeromq#2]
I'm deploying a Tomcat webapp with Mule embedded, using the ZeroMQ transport.

When the app is undeployed, the mule context shuts down successfully, but the ZeroMQ transport threads continue to run, which keeps the sockets in use.

There's a thread here:
ZMQTransportLifecycleAdapter(ZMQTransport).poll(ZMQ$Socket, Boolean, SourceCallback) line: 284  

and here:
ZMQTransport$DispatcherWorker.run() line: 461

**Comment by cjmamo** [comment]
Hey, can you check if this happens as well with the snapshot version?
